// Copies packages/widget-kit into every widget that loads it (docs/decisions.md D-014).
// Homey serves only `widgets/<id>/public/`, so shared widget code has to be a real file there.
//   pnpm kit:sync    write missing or stale copies, remove unused ones
//   pnpm kit:check   report them and fail (CI, pre-commit)
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const HEADER =
  "/* GENERATED by `pnpm kit:sync` from packages/widget-kit/src/widget-kit.js. Do not edit. */\n";
const SOURCE = "packages/widget-kit/src/widget-kit.js";
const LOADS_KIT = /<script\s+src=["']vendor\/widget-kit\.js["']/;

const widgetPublicDirs = (root) => {
  const appsDir = path.join(root, "apps");
  return readdirSync(appsDir)
    .filter((app) => app.startsWith("com.") && existsSync(path.join(appsDir, app, "widgets")))
    .sort()
    .flatMap((app) =>
      readdirSync(path.join(appsDir, app, "widgets"))
        .sort()
        .map((widget) => path.join("apps", app, "widgets", widget, "public")),
    )
    .filter((dir) => existsSync(path.join(root, dir, "index.html")));
};

/** @returns {{ file: string, status: "ok" | "written" | "removed" | "missing" | "stale" | "unused" }[]} */
export const syncKit = (root, { check = false } = {}) => {
  const expected = HEADER + readFileSync(path.join(root, SOURCE), "utf8");
  return widgetPublicDirs(root).flatMap((dir) => {
    const file = path.join(dir, "vendor", "widget-kit.js");
    const full = path.join(root, file);
    const usesKit = LOADS_KIT.test(readFileSync(path.join(root, dir, "index.html"), "utf8"));
    const exists = existsSync(full);

    if (!usesKit) {
      if (!exists) return [];
      if (!check) rmSync(full);
      return [{ file, status: check ? "unused" : "removed" }];
    }
    if (exists && readFileSync(full, "utf8") === expected) return [{ file, status: "ok" }];
    if (check) return [{ file, status: exists ? "stale" : "missing" }];
    mkdirSync(path.dirname(full), { recursive: true });
    writeFileSync(full, expected);
    return [{ file, status: "written" }];
  });
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const problems = syncKit(root, { check }).filter((result) => result.status !== "ok");
  for (const { file, status } of problems) console.log(`${status.padEnd(8)} ${file}`);
  if (check && problems.length > 0) {
    console.log("\nRun `pnpm kit:sync` and commit the result.");
    process.exitCode = 1;
  }
}
